apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnet-basic-ntcdshfw
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/dotnet-basic-ntcdshfw:dbb19837e3ec37f1311d9a74da5c27e0bf59f801@sha256:af4596aff06b649ed1406649b3d8ed98925c586816f918447fe43e991b93977a
          name: container-image
